/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yingenus_pocketchinese_functions_search_PrefixSearcher */

#ifndef _Included_com_yingenus_pocketchinese_functions_search_PrefixSearcher
#define _Included_com_yingenus_pocketchinese_functions_search_PrefixSearcher
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yingenus_pocketchinese_functions_search_PrefixSearcher_RUSSIAN
#define com_yingenus_pocketchinese_functions_search_PrefixSearcher_RUSSIAN 0L
#undef com_yingenus_pocketchinese_functions_search_PrefixSearcher_PINYIN
#define com_yingenus_pocketchinese_functions_search_PrefixSearcher_PINYIN 1L
/*
 * Class:     com_yingenus_pocketchinese_functions_search_PrefixSearcher
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_yingenus_pocketchinese_functions_search_PrefixSearcher_newNative(JNIEnv * , jobject ) ;

/*
 * Class:     com_yingenus_pocketchinese_functions_search_PrefixSearcher
 * Method:    init
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_yingenus_pocketchinese_functions_search_PrefixSearcher_init(JNIEnv * , jobject , jstring , jlong ) ;

/*
 * Class:     com_yingenus_pocketchinese_functions_search_PrefixSearcher
 * Method:    setLanguage
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_yingenus_pocketchinese_functions_search_PrefixSearcher_setLanguage(JNIEnv * , jobject , jint , jlong ) ;

/*
 * Class:     com_yingenus_pocketchinese_functions_search_PrefixSearcher
 * Method:    find
 * Signature: ([BJ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yingenus_pocketchinese_functions_search_PrefixSearcher_find(JNIEnv * , jobject,
                                                                             jbyteArray, jlong);

/*
 * Class:     com_yingenus_pocketchinese_functions_search_PrefixSearcher
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yingenus_pocketchinese_functions_search_PrefixSearcher_deleteNative(JNIEnv * , jobject , jlong ) ;


#ifdef __cplusplus
}
#endif
#endif

